"""initial romiot tables

Revision ID: f966efcac081
Revises: 
Create Date: 2025-11-24 10:17:30.347086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f966efcac081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_number', sa.String(length=255), nullable=False),
    sa.Column('aselsan_order_number', sa.String(length=255), nullable=False),
    sa.Column('aselsan_work_order_number', sa.String(length=255), nullable=False),
    sa.Column('order_item_number', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entrance_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'aselsan_order_number', 'order_item_number', name='uq_work_order_keys')
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_user_id'), 'work_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_work_orders_station_id'), 'work_orders', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_station_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_user_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###

