"""romiot relations

Revision ID: 280ebde453e9
Revises: add_config_table_001
Create Date: 2025-11-21 21:34:18.365543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280ebde453e9'
down_revision = '444ec4fc5a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('workshop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_workshop_id'), 'users', ['workshop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_workshop_id'), table_name='users')
    op.drop_column('users', 'workshop_id')
    # ### end Alembic commands ###
