"""Create initial tables

Revision ID: 2c2d1502a14c
Revises: 3334d70ea5ae
Create Date: 2025-11-05 09:37:21.356866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2d1502a14c'
down_revision = '3334d70ea5ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_query_filters', sa.Column('depends_on', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_query_filters', 'depends_on')
    # ### end Alembic commands ###
