"""Create initial tables

Revision ID: 3334d70ea5ae
Revises: a1b2c3d4e5f6
Create Date: 2025-10-31 09:53:52.743847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3334d70ea5ae'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_query_filters', sa.Column('sql_expression', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_query_filters', 'sql_expression')
    # ### end Alembic commands ###
