"""add deleted_at to reports

Revision ID: 342d76653680
Revises: efd95a7265c4
Create Date: 2026-01-26 10:38:01.906299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342d76653680'
down_revision = 'add_db_config_002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'deleted_at')
    # ### end Alembic commands ###
