"""Create initial tables

Revision ID: 59ca21df192c
Revises: add_cascade_delete
Create Date: 2025-10-10 11:07:30.181192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59ca21df192c'
down_revision = 'add_cascade_delete'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('db_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('theme_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_code'), 'platforms', ['code'], unique=True)
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_table('user_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_platforms_id'), 'user_platforms', ['id'], unique=False)
    op.create_index(op.f('ix_user_platforms_platform_id'), 'user_platforms', ['platform_id'], unique=False)
    op.create_index(op.f('ix_user_platforms_user_id'), 'user_platforms', ['user_id'], unique=False)
    op.add_column('dashboards', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dashboards_platform_id'), 'dashboards', ['platform_id'], unique=False)
    op.create_foreign_key(None, 'dashboards', 'platforms', ['platform_id'], ['id'])
    op.drop_constraint('report_queries_report_id_fkey', 'report_queries', type_='foreignkey')
    op.create_foreign_key(None, 'report_queries', 'reports', ['report_id'], ['id'])
    op.drop_constraint('report_query_filters_query_id_fkey', 'report_query_filters', type_='foreignkey')
    op.create_foreign_key(None, 'report_query_filters', 'report_queries', ['query_id'], ['id'])
    op.add_column('reports', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reports_platform_id'), 'reports', ['platform_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'platforms', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_platform_id'), table_name='reports')
    op.drop_column('reports', 'platform_id')
    op.drop_constraint(None, 'report_query_filters', type_='foreignkey')
    op.create_foreign_key('report_query_filters_query_id_fkey', 'report_query_filters', 'report_queries', ['query_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'report_queries', type_='foreignkey')
    op.create_foreign_key('report_queries_report_id_fkey', 'report_queries', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.drop_index(op.f('ix_dashboards_platform_id'), table_name='dashboards')
    op.drop_column('dashboards', 'platform_id')
    op.drop_index(op.f('ix_user_platforms_user_id'), table_name='user_platforms')
    op.drop_index(op.f('ix_user_platforms_platform_id'), table_name='user_platforms')
    op.drop_index(op.f('ix_user_platforms_id'), table_name='user_platforms')
    op.drop_table('user_platforms')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_code'), table_name='platforms')
    op.drop_table('platforms')
    # ### end Alembic commands ###
