"""Create initial tables

Revision ID: 970b2b76e8dd
Revises: 97ab71a344c8
Create Date: 2025-11-07 16:47:09.693428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '970b2b76e8dd'
down_revision = '97ab71a344c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('layout_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'layout_config')
    # ### end Alembic commands ###
