"""Create initial tables

Revision ID: 97ab71a344c8
Revises: 2c2d1502a14c
Create Date: 2025-11-07 10:19:13.812196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97ab71a344c8'
down_revision = '2c2d1502a14c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('global_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'global_filters')
    # ### end Alembic commands ###
