"""add_layout_config

Revision ID: efd95a7265c4
Revises: add_login_tracking_001
Create Date: 2026-01-26 09:20:29.478714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efd95a7265c4'
down_revision = '280ebde453e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('report_users_user_id_fkey', 'report_users', type_='foreignkey')
    op.drop_constraint('report_users_report_id_fkey', 'report_users', type_='foreignkey')
    op.add_column('reports', sa.Column('layout_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('reports', 'is_direct_link',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'is_direct_link',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('reports', 'layout_config')
    op.create_foreign_key('report_users_report_id_fkey', 'report_users', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('report_users_user_id_fkey', 'report_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
