-- Create the new table
CREATE TABLE IF NOT EXISTS uretim_kalemleri (
    id          SERIAL PRIMARY KEY,
    company_id  INT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    kategori    VARCHAR(100) NOT NULL,
    kalem_adi   VARCHAR(200) NOT NULL
);

-- Clear any existing data to avoid duplicates on re-run
TRUNCATE uretim_kalemleri RESTART IDENTITY CASCADE;

-- Seed data
INSERT INTO uretim_kalemleri (company_id, kategori, kalem_adi) VALUES
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Talaşlı İmalat', 'Mil'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Talaşlı İmalat', 'Flanş'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Talaşlı İmalat', 'Gövde'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Talaşlı İmalat', 'Kapak'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Talaşlı İmalat', 'Burç'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Talaşlı İmalat', 'Pim'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Talaşlı İmalat', 'Kasnak'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Kablaj/EMM', 'Ana Kablo'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Kablaj/EMM', 'Sinyal Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Kablaj/EMM', 'Güç Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Kablaj/EMM', 'Kontrol Kartı'),
  ((SELECT id FROM companies WHERE name = 'Tüm Şirketler'), 'Kablaj/EMM', 'Sensör Modülü'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Talaşlı İmalat', 'Mil'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Talaşlı İmalat', 'Flanş'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Talaşlı İmalat', 'Gövde'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Talaşlı İmalat', 'Kapak'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Talaşlı İmalat', 'Burç'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Kablaj/EMM', 'Ana Kablo'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Kablaj/EMM', 'Sinyal Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Anadolu Holding'), 'Kablaj/EMM', 'Güç Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Talaşlı İmalat', 'Mil'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Talaşlı İmalat', 'Flanş'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Talaşlı İmalat', 'Gövde'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Talaşlı İmalat', 'Pim'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Kablaj/EMM', 'Ana Kablo'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Kablaj/EMM', 'Sinyal Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Kablaj/EMM', 'Güç Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Kablaj/EMM', 'Kontrol Kartı'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Kablaj/EMM', 'Sensör Modülü'),
  ((SELECT id FROM companies WHERE name = 'Türk Telekom'), 'Kablaj/EMM', 'Motor Sürücü'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Talaşlı İmalat', 'Mil'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Talaşlı İmalat', 'Gövde'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Talaşlı İmalat', 'Kasnak'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Kablaj/EMM', 'Ana Kablo'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Kablaj/EMM', 'Sinyal Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Kablaj/EMM', 'Güç Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Kablaj/EMM', 'Kontrol Kartı'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Kablaj/EMM', 'Sensör Modülü'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Kablaj/EMM', 'Motor Sürücü'),
  ((SELECT id FROM companies WHERE name = 'Arçelik A.Ş.'), 'Kablaj/EMM', 'Konnektör Seti'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Talaşlı İmalat', 'Mil'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Talaşlı İmalat', 'Flanş'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Talaşlı İmalat', 'Gövde'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Talaşlı İmalat', 'Kapak'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Talaşlı İmalat', 'Pim'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Talaşlı İmalat', 'Bilezik'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Kablaj/EMM', 'Ana Kablo'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Kablaj/EMM', 'Sinyal Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Kablaj/EMM', 'Güç Kablosu'),
  ((SELECT id FROM companies WHERE name = 'Vestel Elektronik'), 'Kablaj/EMM', 'Kontrol Kartı'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Mil'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Flanş'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Gövde'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Kapak'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Burç'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Pim'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Kasnak'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Talaşlı İmalat', 'Bilezik'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Kablaj/EMM', 'Ana Kablo'),
  ((SELECT id FROM companies WHERE name = 'Ford Otosan'), 'Kablaj/EMM', 'Sinyal Kablosu');
